fn funny_string(input: &str) -> &'static str {
    let bytes = input.as_bytes();
    for i in 0..bytes.len() - 1 {
        if i8::abs(bytes[i] as i8 - bytes[i + 1] as i8)
            != i8::abs(bytes[input.len() - 1 - i] as i8 - bytes[input.len() - i - 2] as i8)
        {
            return "Not Funny";
        }
    }
    "Funny"
}

#[cfg(test)]
mod tests {

    use super::*;

    #[test]
    fn should_return_funny() {
        let input: &str = "acxz";
        let actual: &str = funny_string(input);
        assert_eq!(actual, "Funny");
    }

    #[test]
    fn should_not_return_funny() {
        let input: &str = "bcxz";
        let actual: &str = funny_string(input);
        assert_eq!(actual, "Not Funny");
    }

    #[test]
    fn should_return_funny_long() {
        let input = "qvnqyvztyzrtwsvqtmsyzytmuoqysxqstzvnvotyqvprzrxzsvovzwrumsuzwxruoqtzrywpszywpvytuvyuyrxuyqyskpqvpsuopswsuytlnvzxpvqtxztmnsxpqvqxqwszyrtvyrswquzuvwosuzxuvprsuovnrtmqrzuxrwqtlnvnpwzwzvqtvoruywzsvwyvntysuwopszrvqszsyvwpquvqvyvorwyvxrzvnuywquoqvzywqrzswxumpuntumuxsztxstzxtwstzvxuywxprunrzuvnrzxyszvyqrvyvorzxsvpvytmsvxsknruwqtlpwyvotzxtlmrvywxrxqtuvowzxzvotwzwsxyzxzvxumrwysunrvosuouyqsuyuysklrzxpsvxzrxuzrtlowsxrskprskqvqvqswqrxywpxprvoruvxrwpwsvnsuzystyquwoprtlmnoszwpwswsvxqvxuntwszsvxyvywsuxtvprvzryqtuvxrtxtlsztywpuyzszxywztwqsuzytyztvyzuwptmqvqyqwqwpvoquvotvytzrwzyrvpxzysxsvqumopvnunqxryqyvpwpxpvytytyvwxsxtxquvprzrzuovzrvyswyvpvnprtwyszuvqyzxyqrzvpvnsuwzuxsumquvqwywsywxsvxsuxtzrsxsuovpxumtmpwzrzuxsyvwotywpxqwortvnvovysxyqtwprywqvztxprwqruyqvqrvqywpuovqyzwxptzvnqxquytxrzvyuysknvpxswsxsytxzwpqvqxyqtxrtmuorwrwsvzyszuwrsxruxrzrvnunqumorwskmuxtxuvxqtzryvxzrstxpwyvyzvqwptmszxyzxumqyruxptvwsxprxzvotuyvzxywzyvzwyqtlnszuovnqxyqytzuzyrzxqswoskmryuyqywsyzwovyrxqvxuzyvovzxryzrunqwqtmnvorytzuxtuyrxtuyvzumounrvxywszxuotuwytxsyqtwzwqvprwpwzxuywszytuopqxztwpsuvquywxyvqywpquxunoruwosuotmuxyzvqvouzstuoqxqvwxuwzuxzrvotwpwzsumpxszsxquouwysuyrvwxskptxqsvwosknrwxzyqvotmuwostxtumpuxqtxyuyuxryrxpxsxrsvqtvnqvyvqwovzxuytzskntzrwrwxzuxqxsyzyzvqwzvwsyuvywotmrvzxptwryzwzswzszrvwzvzryuworxqyzxyzuxsvzsxzxpxpwzrsyumqxyvxrstzxyszwyztuovxsywzrsvquwortwszwswrvxuoruyvnpuyqwqxrzvxyvzxszrzxtxsxrtmuzxpwqtzwxtltmnoquwqsvtzxtrqpwowsrourxqywrzsqwrwswyqyrwyurqoksyrxrzvqowzvspvywsxtpmtxuspxvzurqyvtzusztsyxvyrxwysrqwuxwpltxrqyvowowywryurwtyxwyxpwqnvtxqyuyvuqyryvryvsrytqmuswsnupxzwvrxtswtzuyzyxrwpwzusrwrmuouxpwqvzwuyrztyvytqywzurqwrwowqxqwtxtxwspwzurzyuqpltrzsnupxwutyuxpltspnuyuzrwvuqxtrxvtztpwryrmuxpnuxqxuzsowurwzxutsxqxztsrytzsxswvuxpwrxvrzxurqxurnmtrzuxwvtxtyxvyrouszyztsnmtxvzwuxqxsqwrxuxurztyuzxvuztqovzxwuqmtnltyuxtswqxtswtysnuxqyzspvpmtqyxqwuyryvuzwupwqxunvyztxvnvrnupnvrzvtmkszytoupxpovyqxrmtomurzxuyvuxvuswtxwryusmksxtsqmuxunvrzwyxwyrxqmtzuyxuxvowsrqywuxqyspwyxuyuxpnvrwtrzvyrksowourouzytrmtzyuxtytyvpxqouyvnmtytszwuytzuzvrmuowzrxtxuyqwsxtpwpmuysowvyzrwpvqxzrwsrwrzvyztomuyswrxzsqxurzytzwpwowuspxryqxzupxwtzuxskspwzsltqysztrwrqyswtrwuxsrpvzxztyxtpxzurwtrpksyswonvusrzutyrxzwusqysyvtxroksovpksksqwvryuytyxwzuzuzwqyqxqwzrzsyrovowqpnvrwtytzywouqxwtowqvywryxtrysztztltytxqmtrwvsqwvqvuzxztqwzxwunutxszxsyrkswsqwyxwzrkswsqwuyvtxzwzywzszvyszwupwuxtxtmtqxtsrqywyzrpltyxrqvtowzvovqwutqnuqowovtsyztxvqvqvpxwupxwqvrzwomuzwqywuxumksyzrxtxtrpxtztrnuqmtrxzupxuswywvuzvyvsnuywuxpwvurysyxzwsnmuqoupwzxqmurxvsoltywtnuzwqwtomuryvsonvsovpomuyqpksovsqyxzvywsyzvswysrwsyrwzrzyszurzwvrksrxvuytrxtzxtmuyqwuxzuryvsxsrnmtspvovtyumtqpxvtzuowtrqnuxzvspwuxswzwzsqyqowztyspksrnusowpvtsqwvsqvtpxwvqvztpovywunmtxryrwrqytyxqwyuxsyqoksqytxvzvsrxvysxwrztltxuovzvsrqvsyrpovyrpwouxztqwvytrltqvyunurywqyqoupxsnumuysrpwrltrxpwrqpvpwtyvromutouqnvyqv";
        let actual: &str = funny_string(input);
        assert_eq!(actual, "Funny");
    }

    #[test]
    fn should_return_not_funny_long() {
        let input = "jdmwctofewzbqzcqfbvnjjzpwvqvmkswpgsqyhxffyhxyipfkltsvshsnynblhwzoppoxoscnbbnjqrudnnxhvpuwcwhktgxiwmflgizhjmpyfjbrxxyvpursqzdjfcsdnypvhocrzsrhdtxdsxxhtqzkpeuvhpxunnrvdsofkflmxkoqinybdzmtdjokxogmdwkfqxjzdtnceetnqsnvrcowmfilunwwlibdgmckfqlktfwmymhppwlbdslwhjutrvvwhyinpszkyxvwlemzdychtogzxzvqwqofrvsiptrospmeuzfyyhgtwnsvmpljiynythglcyyupmxkmckmkrfjeyeqopbvpnvlwdvxbvrqhqcuunggfkoklszyjcvzrqknshmucemltpfpdnvjyjsjdujnvenmvybpinmlqxvlpddrpxcnitynnhzjnowkpxzwknjcmfobjqtzpumxomkbtllgcirqfqoqfyrrfhrnzlmofblumwvhkiolpgdvxsndqetvnkkmuwzcynvmlstubhhrmjpmdcotihquszipxhqxvnkjiddilmbzwplzryuyhmsbnzplihkgutocvslhelgdbscrsxryjlyvkqitwsyslovjjgrotyqvqroiofiypiubxetwvuojkmrstihmgwhxqwhgbofpxbrxeltchjkqudlomrctplqfhwlkkrbjrsgwfyxlkjdelptygxrvkhcsdocofdxvwfubetnndrsphoomnfjwonqqbshgwgdskwupqheuxwlemysbgdytpolqgrxeyzvjyrxqxckxzwbnxundxlxmyiehcbkzbikyykqylcvmxxyusnypxvdxghejhqkjxuhxeyvqzscxqctkqsyppbmujsfqipyhjigoieeivhhnkzwztwolzcfitmzdbyjjirypucyrkffvhbwzzkkynrghfglfgwpnnnehqdxzjewphsrgedeqvjyzqkevgskufqbuszvbgrsmjjronwfjffixoosvgfpnurjotfqyxikjsdwgybofgxcvlwttbigwcqkuuzuuigdciyhicuojuqefowzqhhmkxxetwzngfpiooovrljzhbdlqclgktttqqyknxwuemcrcsosfyrlcvxrykziesdtjdfxccrfpvxsplktmdgnzdgbpfksxnnirsftvxxkuxejipevtjisoosdsdwrrjbidfbxfbjyxokhdndvymqociswmonfyopeurdbrocqclzfzezxppnrzfnnscutrjwmzbmtoplqzkuznvyfnoxoskbnnugfdeqfeezutkkuugvjdwppkmdcvgqjzvnfbflhkkbftmzprwbvsplecpiyuxjwvvdxcneowgsrtthmqjikxsqyjxxgugcpeenhssuobnhtipgzxnkvhzvpysusbxkgdymusjksxrmfgrfeeqbmrvbpqxjsusxxsltlvedsuqxchehmthxkdbyuzhmvcluvvogrrllnbkqknxxgevrixpcwyptczowxefqupbjrlybxvygcvwlsonqoelpeynbcrqxgsgxdhzdexkhsgsmvhejkpxnnnprehokzwjefigkiprcxjosrrcbibqxnhoroedncnsgwbqepjgotvjkommwmetcljuymynonfvjfnnwvumqpuzdgmbupvvcercspoicvdmcsbzpumglgfqosqikmfnrvpjmdqpzvbcncbexojjwqykkqtvexjvuxggzwwctwdgxflvvugrmgbvvvrcszwowevxzryspdzpklmfhrvswxntsgumfscdwwbxpbseerspeetmwqeuntohbksgdtiyrkvglplqjgfmlxbingccbriccchewqenbbunqfdykhmvgmfusixszfvbicgeulsulohdslbftpcydguwntroxmqhovmkieetrmxlyyprpsrrznopgfdfqtlgqwpycutsiqfiqwyhoryoeofjuhpmczuuxjuygpsphzxxvxelpebutfenouzputltefulvmbdnzziwftlltgeblrofqfblqwowqzsecurbvywztkmprqpejdkbhnlyjbvyznebjudevzfqlrfcjvhrzqrjdchlcelespgbljegklwwcdxmyedxvtgywpjzswdllllvtrefezbhezscfuczpjxlxjmsfpdrcpmuipblqdruclxifyhvkhihrubvjfokwcgerirjkkfnvfucddxolfvcyxyjdmuyocehlwruhwjebdhfigtsnqunnsyphspuwtdhptexrmdtpmywrtqelktzfrrljghhyjoqctpvfsoveotwjkdttvtxmmkwrqesytkdoyxsslovchukswemtylhmvddniwmdgqqfplwzyudhqnzosnhsznewrikzfxeknuqcfpdfjgnysommbuedjjyzqibuffhtbyufnzlxfxxyojmofpsnxrppbpmitsbtsxzgwkfdkddxnonsfgheyvsyleggxhzqgbxcncgweivrvklzrrdppuqzbvfxegplhomtqrrvbmovvbwpsbehxvixrmwwumibzvtrpkppxdnugjjxkpghkpgddczwpjwrgriudymzeyujjfistnbecgggihdwpynxsxruvfubdqjmuqgofhrioyoxgqwwqltiindgrygworkihpvmxotmnjjsyhqpskyzwbhpbploguwmmtzjkvwweiqdogtgptinwqdwfplmkjyxczilufjbobdehxkxstnojplqgxcrgcojcwuxdfxqgctobfltzzhjqtywqcnveeffzbcefcvmdozevnwumffdyfbohnmkqqqrstuyuplzgmddbbynferdkrtqgfcwwtpqpkojbbkgnminmhctmuvvlqorurpsneicpwmqywvnigdwoercyoylfmebgstuwdvnbhdzfbmpgqlvuewurufvjjyodtibvfoynqxsqlhxctsxwornjxlrilhneqnbudyjvvbljhlmcfjxtcnebzwlkdxpumpqpoyklzwvijhkorhjsvmvuiggmfugskvjztumutidcomriuzzslwmueugkoldzgnbcinvbuxeklvtiutzirncvhifvsjwbwxcgmygiwltjgnqdirkyfntlubgplfphcsmnqtuofnxmcpqjhzilndvjfexqioylgnzwgvmmkjbmbquhscrhhopltpdbdcnlomjvjuktgkhgzbmtffznurxogbqkeewtrfobzxvhhcmjczcieeuxusncuenzhksxogzpguvmvjwzibhleclzvzbrdnslwklnrkewhclckhdsjkfmnrlkrndtbufyepnwbrthselempvvbbjnrwyijdelwkmcbyybrrklwwpklkfmmqbgmcpweskbcveevchnuqzqmodybjmmynrmohltbutfpzikboyxgbptorsobedysvniexcfrwlivutyluvqukmiceycjdcexqlcnoielsngoheybbpulbemgcpqesvejhfvwochgqpvwuuwvjsglwtszkkecghmonkkbntididzcwxwhsetoynnixsmfbzspjepvwyygczizygjqkcekrtsonguofoforulqulvvkfxjlgywjfgzzzpmfjcmwhcqdogwzdujirtsyuojyvlxvzlclnpjtsyvhgtgjnoqgkkgezrcucbrdlvnxkysdwpjfjonxefgnolsnevjfvbijvwifwbjtrtzchmcnqhcgtusxpbenblvxkdfgfnbyjzzrnbefhikdcccsfffhqcfchjjnxklglnxynddwknbnqcgugmcxqiyysilptyxelwcxbhvltvzjwhgdthzlqbjiivybtxgetiewobhjyitupyykhbuwdfekzfmvcryvberqfzydjsyxszhzcdxehcpjidejtegwiwmoxlsjfsgwrpvutvxbymlgoooktuibstqsgkbmdgjvwgqqbpsyedetssflmmogiexpqxcugkpcrhtsylqcnwuhqcscnghwlhmdenwjwonpwghurzvgvsplvhoiowfbdsejfztdpgrmobghzeowxdjslycywicczfkegdixlcjycofbtsyqvhkgfmhdtietonyvsjsdkbblrfnmyldttmczxictrgofuocmwuoiwqspuhcvrgokrrjrynmpszvmnzbmtotrhojdumxormxkfjdexouppsdfrdsmtlfzbpcvbzjrnietsgwpwtglnlrgnjriwxjwnltnmehboktgrsxnnfbzptffdxmbuxwjkswvvfxjosrhmqwyuyzkrgovdcvzyuiimgfjkeuzwljidfjwdiivqxrszotziekvjqhvubwsnfcpjklnuvjkscetpxvzdfwnudiodfirjkgutthporbisfekeyjgdhsymdpojwirgnnciusxltggxjpdjzilicltgzkoyrggeuhooclcusjrbxvjydvggjzmijzizhofcwsrxgurxdkbcflcjjiprjdbrejslwwosrhqycjvgtxixjjjrszibcirfqlrokhjbobbrjvwetgcermujlekmndseomtzscciccynyvqrbrwrfsbpvmdjqvogjhfblgjmhhygepyfixxnpzelnhvecjlkrqmcxwqhgqmjfmppjpebohlcnghqqrchjojhmbnrqbdxotmzirzyxmznrifhbhpkwzsizhcqhgnwybvjruhqgifypkhrsyboxuxzbbpjgeghgbpyxvofdvgthokymnmkhljimzqrfvxkyoixjxcnsjgyxqyjdmulxfslejekgetgrbdbyfpspvtmnrxrgrcfwwpcfsmmxhspiuribgcqduepobitukzsgotmihzgorwxonfqugixdmosownigmznzvyjezorrkqhyuwtdfshsgygclojypvxmviqvwhoizwh";
        let actual: &str = funny_string(input);
        assert_eq!(actual, "Not Funny");
    }
}
