pub mod cat_mouse;
pub mod divisible_sum_pairs;
pub mod distinct_pairs;
pub mod number_converter;
pub mod find_digits;
pub mod fair_rations;
pub mod pairs;
pub mod fizz_buzz;
pub mod ice_cream_parlor;